server:
  port: 8046

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: BE1
          uri: http://localhost:8081/
          predicates:
            - Path=/be1/**
          filters:
            - RewritePath=/be1/(?<path>.*), /$\{path}


